"""Typed protocols for dependency injection boundaries.

These protocols define the contracts between the application layer and
driver/infrastructure adapters, enabling static type checking without
coupling to concrete implementations.
"""

from __future__ import annotations

import asyncio
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class DriveProtocol(Protocol):
    """Minimal contract for the motor-drive adapter used by the app layer."""

    is_connected: bool

    # -- telemetry / state ---------------------------------------------------

    async def get_status(self) -> dict[str, Any]: ...
    async def get_status_live(self) -> dict[str, Any]: ...
    async def get_position(self) -> int: ...
    async def is_motion(self) -> bool: ...
    async def is_homed(self) -> bool: ...
    async def read_u16(self, index: Any, sub: Any) -> int: ...
    async def read_i32(self, index: Any, sub: Any) -> int: ...
    async def read_i8(self, index: Any, sub: Any) -> int: ...
    def telemetry_latest(self) -> Any: ...

    # -- motion commands -----------------------------------------------------

    async def jog_stop(self, **kwargs: Any) -> None: ...
    async def jog_start(self, **kwargs: Any) -> None: ...
    async def jog_update(self, **kwargs: Any) -> None: ...
    async def move_to_position(self, **kwargs: Any) -> None: ...
    async def home(self, **kwargs: Any) -> Any: ...
    async def fault_reset(self, **kwargs: Any) -> None: ...
    async def quick_stop(self, **kwargs: Any) -> None: ...
    async def stop(self, **kwargs: Any) -> None: ...


@runtime_checkable
class AppStateProtocol(Protocol):
    """Typed view of the attributes DriveService reads from ``app.state``."""

    drive: DriveProtocol | None
    event_bus: Any
    motor_lock: asyncio.Lock | None
