[mypy]
python_version = 3.12
ignore_missing_imports = True
warn_return_any = True
warn_unused_configs = True
pretty = True
show_error_codes = True
follow_imports = normal
plugins = pydantic.mypy
files = main.py, app/
exclude = (^drivers/|^drivers\.zip$|^main-2\.py$)

[mypy-drivers.*]
ignore_errors = True

[mypy-tests.*]
ignore_errors = False
